org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
unityStreamingAssets=
unityTemplateVersion=19
unityProjectPath=D:/Documents/Capstone_Project/Thesis_Integrate_UWB_For_Lab/Mobile_Application/uwb_positioning/unity/UWB FOR LAB
unity.projectPath=D:/Documents/Capstone_Project/Thesis_Integrate_UWB_For_Lab/Mobile_Application/uwb_positioning/unity/UWB FOR LAB
unity.debugSymbolLevel=none
unity.buildToolsVersion=35.0.0
unity.minSdkVersion=23
unity.targetSdkVersion=35
unity.compileSdkVersion=35
unity.applicationId=com.UnityTechnologies.com.unity.template.urpblank
unity.abiFilters=armeabi-v7a,arm64-v8a
unity.versionCode=1
unity.versionName=0.1.0
unity.namespace=com.UnityTechnologies.com.unity.template.urpblank
unity.androidSdkPath=C:/Users/kyduy/AppData/Local/Android/sdk
unity.androidNdkPath=C:/Users/kyduy/AppData/Local/Android/Sdk/ndk/android-ndk-r27c
unity.androidNdkVersion=27.2.12479018
unity.jdkPath=D:/ProgramFiles/Java/jdk-17.0.9
unity.javaCompatabilityVersion=VERSION_17
android.useAndroidX=true
android.enableJetifier=true
android.bundle.includeNativeDebugMetadata=false
org.gradle.welcome=never